services:
    xm-nginx-service:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: xm-nginx-container
        volumes:
            - ./../:/var/www/xm/
        ports: ['7000:80']
    xm-php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: xm-php-container
        ports: ['7001:9000']
        volumes:
            - ./../:/var/www/xm/
